### ISSUE TITLE
Can this be used inside `useSyncExternalStore` from react ?

### ISSUE THREAD

**Issue by panteliselef** [florian-lefebvre/astro-als#2]
Hey @florian-lefebvre great work, 

I've been following the same mentality/pattern for building [astro-clerk-auth](https://github.com/panteliselef/astro-with-clerk-auth/blob/6ade8f9a79320e0f29e531fe395f1e688e4324cd/packages/astro-clerk-auth/README.md).

Anyone who installs the package and uses react in their astro app will get [this warning](https://github.com/panteliselef/astro-with-clerk-auth/blob/6ade8f9a79320e0f29e531fe395f1e688e4324cd/packages/astro-clerk-auth/README.md#known-issues) at build time.

Do you by any chance have any advice on how to solve this issue ?
(sorry did not know how else to contact you)

**Comment by florian-lefebvre** [comment]
Mmmh so the issue is that you're importing the als client side. To solve the issue, I'm using a virtual import that is different on server and on client so `async_hooks` are only imported client-side. https://github.com/florian-lefebvre/astro-als/blob/main/package/src/integration.ts#L86-L101

**Comment by panteliselef** [comment]
I'm closing this one, thanks for the response 💯
